language: python
os: linux
env:
  global:
  - CIBW_SKIP=cp34-*
  - CIBW_BUILD=cp3?-manylinux*
  - CIBW_MANYLINUX_X86_64_IMAGE=manylinux1
  - CIBW_MANYLINUX_I686_IMAGE=manylinux1
  - CIBW_TEST_COMMAND="python {project}/test.py"
  # Note: TWINE_PASSWORD is set to an API token in Travis settings
jobs:
  include:
  - services: docker
install:
  - python -m pip install -U setuptools wheel twine cibuildwheel==1.1.0
script:
  - python -m cibuildwheel --output-dir ./wheelhouse
  - ls wheelhouse

deploy:
  provider: releases
  api_key:
    secure: ma4vJ+kb33ESsORli3YMk9+WLRSBB4FvAT0ALIC6HpqJLqFDJldMr9TgJrLNwPnh4fhI/+pFdbeMNrfE6S57gfhfduJQIeiG7ay+9WexsZAUovT/yP+67d6XhxEQ7sf8AyqJuE1sPOXOBfVrVjT3o2BpfkQkRfCRKZpeGlwGNKG9nEGccSeZX1cigcqweWObE33Rim6EEOLbJl8zm2YK5nvIy3i7RxK9bK/PyyVnm1le5tW0gfDkcbdFYeULNjO2Ekdu52Ay9FIVwCJYGx4Xr/8pF09plNeOs/y/p7cwbD0USOxsapa9xtwbBG6DhE2msNoNDilA3lEPLMtSqnugDQvgPRRKj6Fc0j24A/FYAi25b4lK8hqmIGlY85LYQYPj8lVxWuv8ygM0ZMGyhJ3aolC4XUkt/TO0LKTsgP7DtM1MXV09H9T7fAFLpBKvkJnOBtCCfV12PVxaVVgfCEKymFZvZzOjgKhIila9iSmLLuEq8NPfJC8cKCNOm6RBv9CG2ZRltFXmkNUNSitsg5QyDuWK5ZxcWV/wyztx/FfG1v5lIQs4a/UaJwdnsUX+/0nK8rl2TCorFt0yAfD+3sCEuBoev3C6SKK8H4O1FDmurBoEHjdjzYUaumwUH+ZbTvijdD3zQMH04l04mD9riMXFfuyXMLJ6jf02Yn6RXFaFU8E=
  file: wheelhouse/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: aforren1/pygamemode
    tags: true